In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
arr = np.array(my_list)

In [3]:
print(arr)

[1 2 3]


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(3,)

In [2]:
my_list1 = [1,2,3,4,5]
my_list2 = [4,5,6,7,8]
my_list3 = [7,8,9,8,6]
arr = np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [7 8 9 8 6]]


In [3]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 4],
       [5, 6, 7],
       [8, 7, 8],
       [9, 8, 6]])

In [5]:
arr[0:2]

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [7]:
arr[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [8]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [12]:
arr[1:2,1:4]

array([[5, 6, 7]])

In [8]:
arr = np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [9]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
arr[3:]=100
arr

array([  0,   2,   4, 100, 100])

In [11]:
arr1=arr
arr1

array([  0,   2,   4, 100, 100])

In [12]:
arr1[3:]=500
arr1

array([  0,   2,   4, 500, 500])

In [13]:
# Both Aray Values become same
arr

array([  0,   2,   4, 500, 500])

In [14]:
val = 2
arr < 2

array([ True, False, False, False, False])

In [16]:
val = 2
arr[arr < 500]

array([0, 2, 4])

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.random.rand(3,3)

array([[0.00215696, 0.87259906, 0.48600721],
       [0.6313912 , 0.19174654, 0.64582449],
       [0.8826246 , 0.0541901 , 0.9267511 ]])